import {
  researcherWorkspaceSchema,
} from "@research-os/types";

export const dashboardSnapshot = researcherWorkspaceSchema.parse({
  profile: {
    id: "profile-main",
    owner: { type: "user", id: "user-gongjae" },
    displayName: "GongJae",
    koreanName: "조영재",
    englishName: "Youngjae Jo",
    preferredName: "GongJae",
    romanizedName: "GongJae",
    headline: "Graduate researcher building a structured operations system for research life.",
    primaryEmail: "gongjae@example.com",
    emails: ["gongjae@example.com", "gongjae@lab.example.com"],
    nationalResearcherNumber: "NR-2026-001",
    orcid: "0000-0000-0000-0000",
    primaryInstitution: "ResearchPages Pilot Lab",
    primaryDiscipline: "Human-centered systems",
    phones: ["010-0000-0000"],
    keywords: ["profile vault", "funding context", "document reuse", "lab operations"],
    links: [
      {
        kind: "github",
        label: "GitHub",
        url: "https://github.com/gongjae",
      },
      {
        kind: "homepage",
        label: "Research homepage",
        url: "https://researchpages.example/gongjae",
      },
      {
        kind: "google_scholar",
        label: "Google Scholar",
        url: "https://scholar.google.com/citations?user=gongjae",
      },
    ],
    publicProfile: {
      enabled: false,
    },
  },
  affiliations: [
    {
      id: "aff-1",
      owner: { type: "user", id: "user-gongjae" },
      institutionName: "Yonsei University",
      department: "Graduate School",
      labName: "ResearchPages Pilot Lab",
      organizationType: "university",
      roleTitle: "Master's Student",
      roleTrack: "student",
      appointmentStatus: "active",
      startDate: "2025-03-01",
      active: true,
      relatedFundingIds: ["fund-1", "fund-2"],
      notes: "Primary academic affiliation and research home base.",
    },
    {
      id: "aff-2",
      owner: { type: "user", id: "user-gongjae" },
      institutionName: "Industry Collaboration Center",
      organizationType: "company",
      roleTitle: "Project Research Assistant",
      roleTrack: "industry",
      appointmentStatus: "active",
      startDate: "2025-09-01",
      active: true,
      relatedFundingIds: ["fund-3"],
      notes: "Tracks project rules separately from the university timeline.",
    },
  ],
  funding: [
    {
      id: "fund-1",
      owner: { type: "user", id: "user-gongjae" },
      title: "Graduate Scholarship",
      sourceType: "scholarship",
      compensationKind: "scholarship",
      providerName: "Yonsei Graduate School",
      currency: "KRW",
      amount: 1800000,
      cadence: "monthly",
      startDate: "2025-03-01",
      active: true,
      linkedAffiliationId: "aff-1",
      restrictions: ["Requires enrolled status", "Cannot overlap with certain assistantships"],
    },
    {
      id: "fund-2",
      owner: { type: "user", id: "user-gongjae" },
      title: "Lab Research Assistant Payroll",
      sourceType: "assistantship",
      compensationKind: "payroll",
      providerName: "ResearchPages Pilot Lab",
      projectName: "Researcher workflow platform prototype",
      currency: "KRW",
      amount: 900000,
      cadence: "monthly",
      startDate: "2025-03-01",
      active: true,
      linkedAffiliationId: "aff-1",
      restrictions: ["Subject to university payroll cap"],
    },
    {
      id: "fund-3",
      owner: { type: "user", id: "user-gongjae" },
      title: "Industry Joint Project Support",
      sourceType: "industry",
      compensationKind: "grant",
      providerName: "Industry Collaboration Center",
      projectName: "Document operations pilot",
      currency: "KRW",
      cadence: "custom",
      startDate: "2025-09-01",
      endDate: "2026-02-28",
      active: false,
      linkedAffiliationId: "aff-2",
      restrictions: ["Only available during active project months"],
      notes: "Shows that project-linked support can end independently from the profile.",
    },
  ],
  documents: [
    {
      id: "doc-1",
      owner: { type: "user", id: "user-gongjae" },
      title: "Academic CV Working Draft",
      documentCategory: "reference_archive",
      documentType: "cv",
      sourceKind: "mixed",
      status: "draft",
      visibility: "private",
      summary: "Base CV file that stays updated so new contacts and applications start from current source data.",
      originalFileName: "Academic_CV_Working_Draft.md",
      mimeType: "text/markdown",
      fileExtension: "md",
      fileSizeBytes: 4096,
      fileAssetId: "asset-profile-cv-working-draft",
      tags: ["cv", "career-kit", "profile"],
      relatedFundingIds: [],
      relatedAffiliationIds: ["aff-1", "aff-2"],
      updatedOn: "2026-03-16",
    },
    {
      id: "doc-2",
      owner: { type: "user", id: "user-gongjae" },
      title: "Statement of Purpose Core Draft",
      documentCategory: "application_admin",
      documentType: "statement",
      sourceKind: "mixed",
      status: "draft",
      visibility: "private",
      summary: "Reusable SOP paragraphs that can be refined over time and remixed for each opportunity.",
      originalFileName: "Statement_of_Purpose_Core_Draft.md",
      mimeType: "text/markdown",
      fileExtension: "md",
      fileSizeBytes: 4096,
      fileAssetId: "asset-profile-sop-core-draft",
      tags: ["sop", "statement", "career-kit"],
      relatedFundingIds: [],
      relatedAffiliationIds: ["aff-1", "aff-2"],
      updatedOn: "2026-03-15",
    },
    {
      id: "doc-3",
      owner: { type: "user", id: "user-gongjae" },
      title: "Short Bio and Contact Kit",
      documentCategory: "reference_archive",
      documentType: "bio",
      sourceKind: "mixed",
      status: "active",
      visibility: "private",
      summary: "Ready-to-copy short bio, contact lines, and public profile snippets for homepage and outreach use.",
      originalFileName: "Short_Bio_and_Contact_Kit.md",
      mimeType: "text/markdown",
      fileExtension: "md",
      fileSizeBytes: 3072,
      fileAssetId: "asset-profile-bio-contact-kit",
      tags: ["bio", "homepage", "contact"],
      relatedFundingIds: [],
      relatedAffiliationIds: ["aff-1", "aff-2"],
      updatedOn: "2026-03-14",
    },
    {
      id: "doc-4",
      owner: { type: "user", id: "user-gongjae" },
      title: "Research Portfolio Highlights",
      documentCategory: "reference_archive",
      documentType: "portfolio",
      sourceKind: "mixed",
      status: "draft",
      visibility: "private",
      summary: "Continuously updated portfolio notes covering representative projects, strengths, and public links.",
      originalFileName: "Research_Portfolio_Highlights.md",
      mimeType: "text/markdown",
      fileExtension: "md",
      fileSizeBytes: 4096,
      fileAssetId: "asset-profile-portfolio-highlights",
      tags: ["portfolio", "career-kit", "projects"],
      relatedFundingIds: [],
      relatedAffiliationIds: ["aff-1", "aff-2"],
      updatedOn: "2026-03-13",
    },
    {
      id: "doc-5",
      owner: { type: "user", id: "user-gongjae" },
      title: "2026 National Scholarship Motivation Statement",
      documentCategory: "application_admin",
      documentType: "scholarship_answer",
      sourceKind: "mixed",
      status: "active",
      visibility: "private",
      summary: "Reusable answer bank content for scholarship applications.",
      originalFileName: "2026_National_Scholarship_Motivation_Statement.docx",
      mimeType:
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      fileExtension: "docx",
      fileSizeBytes: 284672,
      tags: ["scholarship", "motivation", "2026"],
      relatedFundingIds: ["fund-1"],
      relatedAffiliationIds: ["aff-1"],
      updatedOn: "2026-03-01",
    },
    {
      id: "doc-6",
      owner: { type: "user", id: "user-gongjae" },
      title: "Research Plan Core Narrative",
      documentCategory: "research",
      documentType: "research_plan",
      sourceKind: "rich_text",
      status: "draft",
      visibility: "private",
      summary: "Core paragraphs to remix across institution-specific forms.",
      originalFileName: "Research_Plan_Core_Narrative.docx",
      mimeType:
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      fileExtension: "docx",
      fileSizeBytes: 192448,
      tags: ["plan", "proposal", "reusable"],
      relatedFundingIds: [],
      relatedAffiliationIds: ["aff-1", "aff-2"],
      updatedOn: "2026-03-05",
    },
    {
      id: "doc-7",
      owner: { type: "user", id: "user-gongjae" },
      title: "Default Lab Pitch Deck Template",
      documentCategory: "template_form",
      documentType: "template",
      sourceKind: "file",
      status: "active",
      visibility: "private",
      summary: "Personal slide template archive for future lab and proposal work.",
      originalFileName: "Default_Lab_Pitch_Deck_Template.pptx",
      mimeType:
        "application/vnd.openxmlformats-officedocument.presentationml.presentation",
      fileExtension: "pptx",
      fileSizeBytes: 5177344,
      tags: ["ppt", "template", "lab"],
      relatedFundingIds: [],
      relatedAffiliationIds: [],
      updatedOn: "2026-02-14",
    },
  ],
  timetable: {
    id: "tt-2026-spring",
    owner: { type: "user", id: "user-gongjae" },
    term: {
      year: 2026,
      season: "spring",
      label: "2026 Spring Semester",
    },
    entries: [
      {
        id: "slot-1",
        scheduleId: "schedule-advanced-research-methods",
        courseTitle: "Advanced Research Methods",
        courseCode: "RSH601",
        dayOfWeek: "monday",
        startTime: "09:00",
        endTime: "10:30",
        kind: "class",
        location: "Engineering Hall 301",
      },
      {
        id: "slot-2",
        scheduleId: "schedule-lab-weekly-meeting",
        courseTitle: "Lab Weekly Meeting",
        dayOfWeek: "wednesday",
        startTime: "14:00",
        endTime: "15:30",
        kind: "meeting",
        location: "Pilot Lab Conference Room",
      },
      {
        id: "slot-3",
        scheduleId: "schedule-proposal-writing-block",
        courseTitle: "Proposal Writing Block",
        dayOfWeek: "friday",
        startTime: "10:00",
        endTime: "12:00",
        kind: "research",
        notes: "Reserved writing time for scholarship and grant submissions.",
      },
    ],
  },
});
